// <auto-generated />
namespace RoboticsWebsite.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addqueryable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addqueryable));
        
        string IMigrationMetadata.Id
        {
            get { return "201503260352149_addqueryable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
